---
title: "Lab 2 Advanced Data Visualization"
author: "Gavin Martinez"
date: "2023-04-13"
output: html_document
---

## Part 1: Identifying Bad Visualizations

### Dissecting a Bad Visualization

1.  While there are certainly issues with this image, do your best to tell the story of this graph in words. That is, what is this graph telling you? What do you think the authors meant to convey with it?

    **The graph is trying to show the percentage of people that believe vaccines are safe. Each facet is a region. Each point within a region represents a country within that region. The x-axis represents percentage points, and the bold vertical line for each region is the median percentage of citizens that believe vaccines are safe. The authors most likely meant to convey the difference in the variability of vaccine acceptance from region to region as well as variability from country to country within the region. There seemed to be an attempt to convey something by making each region its own pane, but it is not quite clear what that is by looking at the plot.**

2.  List the variables that appear to be displayed in this visualization.

    **The variables that appear to be displayed in this visualization are region, country, percentage of citizens within each country that believe vaccines are safe, and median percentage of citizens that believe vaccines are safe among countries within a given region.**

3.  Now that you're versed in the grammar of graphics (ggplot), list the aesthetics used and which variables are specified for each.

    **x = percentage of citizens within each country that believe vaccines are safe.**

    **y = index of country**

    **fill = region**

4.  What type of graph would you call this?

    **I would call this a faceted scatter plot by region of percentage of citizens within each country that believe vaccines are safe by their sorted index.**

5.  List all of the problems or things you would improve about this graph.

    -   **no meaningful y-axis**

    -   **redundant legend**

    -   **crowded visualizations**

### Improving the Bad Visualization

```{r data and libraries}
library(tidyverse)
library(here)

vac <- read_csv(here('vaccines.csv'))
```
